name: deploy
on:
    push:
        branches:
            - main

concurrency:
    group: ${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: true

jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4.1.1
            - uses: actions/setup-node@v4.0.0
              with:
                  node-version: '21'
            - run: npm ci
            - run: npm run build --workspaces
            - uses: FirebaseExtended/action-hosting-deploy@v0
              with:
                  repoToken: '${{ secrets.GITHUB_TOKEN }}'
                  firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_PORTFOLIO_77EBD }}'
                  channelId: live
                  projectId: portfolio-77ebd
                  entryPoint: 'packages/client'
